android/app/src/main/res/values-night-v31/styles.xml
android/app/src/main/res/values-night/styles.xml
android/app/src/main/res/values-v31/styles.xml
android/app/src/main/res/values/styles.xml
lib/main.dart
pubspec.lock
pubspec.yaml

- (Android) Splash screen not taking Fullscreen
- Showing splash screen for some extended time (690ms)

(Android) Splash Screen Fix

---

README.md

- updated readme web support as in beta mode

README added Web beta support

---

lib/pages/HomePage/functions/get_image.dart
lib/pages/HomePage/home_page.dart

Search result completely random for camera captured images

REFACTOR: removed select from camera option

---

lib/main.dart
lib/themes/app_theme.dart
lib/themes/system_ui_theme.dart

- Makes **status bar** as same color as `appBar`
- Makes **system nav bar** as same color as `scaffold`/`bottom nav`
- Makes app looks immersive
- Feels nice as UI

(Android) Added edge to edge display theme

---

web/index.html

- `Open Graph Images` to enable **social media** previews
- Formatted `HTML` Code using Prettier formatter

Website preview for social media

---

lib/pages/HomePage/home_page.dart
lib/pages/HomePage/widgets/image_preview.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

- Add drag and drop feature for web (also supports on android)
- Converted _Image Preview_ box in **Home Page** to able to receive dropped files.
- Changed _Image Preview_ box border to _Dashed lines_ if no image is selected.
- Changed _Image Preview_ box `Text` to inform **drag and drop** is available
<br />
Does **NOT**  have any Breaking Changes
Resolves #13

(Web) Drag and drop feature

---

.github/workflows/flutter-ci.yml

- Checks for any formatting issues
- Checks for any errors in code

FEAT: Workflow to check pushes and PRs on main

---

.github/workflows/code_quality.yml

- Changed workflow file name
- Change workflow name
- Separated lint and error checking in jobs

REFACTOR: separated jobs for lint and error checks

---

.github/workflows/build.yml

Added jobs to build flutter in android and web platforms
- Builds apk
- Builds app bundle
- Builds with `flutter build web`

FEAT: workflow to checks build on supported platforms

---

pubspec.lock
web/index.html
web/splash/splash.js

(Web) FIX: branding image source link broken

---

web/index.html

- Added image with discord link share preview dimensions
- Updated link preview images

FEAT: added image for discord link preview

---

pubspec.lock

Downgraded firebase dependencies

FIX: bugs for breaking changes in v9 JS firebase

---

lib/pages/HomePage/widgets/paste_listener.dart

- requesting focus whenever dep changes

FIX: paste won't work after navigation

---

pubspec.lock

CHORE: update dependencies

---

pubspec.lock

- Fixes firebase auth web persistence location problem

CHORE: updated dependencies

---

android/app/src/main/res/values-night-v31/styles.xml
android/app/src/main/res/values-v31/styles.xml
flutter_native_splash.yaml

- Added background color for splash screen for android 12

FIX: splash screen bg color not set for android 12

---

web/index.html

REFACTOR: added lang attr in html

---

lib/pages/AnimeSearchPage/widgets/top_result.dart
lib/pages/HistoryPage/widgets/record_tile.dart

- Added black background for video player for 4:3 ratio videos
- Added loading placeholder for image in history page
- Added error icon for image in history page

REFACTOR: added some decorations

---

lib/pages/AnimeSearchPage/anime_search_page.dart
lib/pages/AnimeSearchPage/functions/get_image_search.dart

- Only retry if failed due to `Concurrency limit exceeded`
- Total tries limited to `3`
- If failed, throw exception and show error toast

REFACTOR: limited number of retries for failed searches

---

pubspec.lock
pubspec.yaml

- Removed `cupertino_icons` package from `pubspec.yaml` file (as not directly used)

Updated dependencies to latest

---

web/index.html

- Added missing `<meta property="og:" />` tags
- Image not shown in full view for link preview

Added Open Graph preview content

---

lib/pages/HomePage/home_page.dart
lib/pages/HomePage/widgets/image_preview.dart

- If image is broken null it and show error toast

FIX: search img available for broken image

---

android/app/src/main/res/values-night-v31/styles.xml
android/app/src/main/res/values-night/styles.xml
android/app/src/main/res/values-v31/styles.xml
android/app/src/main/res/values/styles.xml
web/index.html

XML and HTML should define type and version as 1st line
- Moved copyright notice below doctype and version

FIX: xml and html format not correct

---

lib/pages/HomePage/widgets/my_search_button.dart
pubspec.lock

- Updates dependencies for flutter v3.3.0
- Updates minor pub packages
- Removes deprecated methods

CHORE: Updated minor dependencies

---

lib/screens/MainScreen/main_screen.dart
pubspec.lock
pubspec.yaml

Better UX when using tablet or desktop
- Replacing _bottom nav bar_ with _navigation bar_
- Using _navigation rail_ for bigger screens
resolves #54

FEAT: responsive nav bar for big screens

---

pubspec.lock

Updated chewie dependency to fix it

FIX: video player play button too large
